version: '3'

services:
  app:
    build: ./proxy
    ports:
      - "6060:6060"
    networks:
      - mylocal

  server:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - ./proxy/docs/swagger.yaml:/swagger.yaml
    networks:
      - mylocal


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - app
      - swagger
    networks:
      - mylocal

networks:
  mylocal:
    driver: bridge
